Repository Techeer-FM-Studio/frontend, pull requests merged in 2023-04, with the labels that each got.

#16 Feat/9 달력 컴포넌트 레이아웃, 기초 기능들 제작
  package-lock.json
  package.json
  src/components/calendar/Calendar.tsx
  src/pages/index.tsx
  src/styles/components/calendar/Calendar.module.scss
  src/styles/pages/MainPage.module.scss
  yarn.lock
Labels: 기능구현

#18 Feat/17 헤더 컴포넌트 초기 구현
  package.json
  public/Logo.png
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/components/common/Header.tsx
  src/pages/banner/list.tsx
  src/pages/index.tsx
  src/styles/components/banner/BannerItem.module.scss
  src/styles/components/common/Header.module.scss
  yarn.lock
Labels: 기능구현

#23 Feat/22 MainPage에서 Banner 여러 장 넘어가는 레이아웃 추가
  package-lock.json
  public/temp_images/BannerTempImage1.png
  public/temp_images/BannerTempImage2.png
  public/temp_images/BannerTempImage3.png
  public/temp_images/BannerTempImage4.png
  public/temp_images/BannerTempImage5.png
  src/components/banner/BannerMainLayout.tsx
  src/pages/index.tsx
  src/styles/components/banner/BannerMainLayout.module.scss
  src/styles/pages/MainPage.module.scss
  yarn.lock
Labels: 기능구현

#27 chore/26 : 패키지 관리자 yarn으로 교체 완료
  package-lock.json
  yarn.lock
Labels: 환경설정

#25 feat/24 : 헤더 메인페이지 POC 디자인에 맞게 수정
  src/components/common/Header.tsx
  src/pages/index.tsx
  src/styles/components/common/Header.module.scss
  src/styles/pages/MainPage.module.scss
  yarn.lock
Labels: 리펙토링

#28 Feat/13 배너 리스트 컴포넌트/페이지 초기 구현
  next.config.js
  package.json
  src/apis/createAxios.ts
  src/apis/getBannerList.ts
  src/components/banner/BannerItem.tsx
  src/components/banner/BannerList.tsx
  src/pages/api/v1/banner/page.ts
  src/pages/banner/[slug].tsx
  src/pages/banner/list.tsx
  src/styles/components/banner/BannerItem.module.scss
  src/styles/components/banner/BannerList.module.scss
  src/styles/components/banner/BannerList.moudle.scss
  src/styles/pages/BannerListPage.module.scss
  src/styles/pages/bannerPage.moudle.scss
  src/types/banner.ts
  yarn.lock
Labels: 기능구현

#36 Feat/34 UserInfo Layout 제작
  public/temp_images/UserInfoTempImage.png
  src/components/user/UserInfoMainLayout.tsx
  src/pages/index.tsx
  src/styles/components/user/UserInfoMainLayout.module.scss
  src/styles/pages/MainPage.module.scss
Labels: 기능구현

#38 Feat/31 NextRoutineLayout 구현
  src/apis/getNextRoutine.ts
  src/components/routine/NextRoutineLayout.tsx
  src/pages/api/v1/tasks/list.ts
  src/pages/index.tsx
  src/styles/components/routine/NextRoutineLayout.module.scss
  src/types/routine.ts
Labels: 기능구현

#40 Refactor/39 NextRoutineLayout 코드개선작업
  src/components/routine/NextRoutineLayout.tsx
  src/pages/api/v1/tasks/list.ts
  src/utils/getTimeLeftDisplay.ts
  src/utils/updateTaskStatusAndTimeLeft.ts
Labels: 리펙토링

#42 Feat/30 달력에 일정 있는지 여부 표시하기
  src/apis/fetchTaskData.ts
  src/components/calendar/Calendar.tsx
Labels: 기능구현

#41 Refactor/29 필요한 주석 추가
  src/pages/index.tsx
Labels: 리펙토링

#44 Feat/20 Routine 일정 추가하기 나타나도록 하기
  src/apis/fetchTaskData.ts
  src/components/calendar/Calendar.tsx
  src/components/routine/NextRoutineLayout.tsx
  src/components/routine/RoutineLayout.tsx
  src/pages/api/v1/tasks/list.ts
  src/pages/index.tsx
  src/styles/components/routine/RoutineLayout.module.scss
  src/utils/getTimeLeftDisplay.ts
  src/utils/updateTaskStatusAndTimeLeft.ts
Labels: 기능구현

#47 Feat/35 배너 생성페이지 구현
  package.json
  src/apis/postBannerInfo.ts
  src/apis/postImages.ts
  src/pages/_app.tsx
  src/pages/api/v1/banners/custom/index.ts
  src/pages/api/v1/images/index.ts
  src/pages/banner/create/index.tsx
  src/styles/components/common/Header.module.scss
  src/styles/pages/BannerCreatePage.module.scss
  tsconfig.json
  yarn.lock
Labels: 기능구현

#48 Feat/30 일정 불러오기
  src/apis/fetchTaskData.ts
  src/components/calendar/Calendar.tsx
  src/components/routine/RoutineLayout.tsx
  src/pages/api/v1/tasks/list.ts
  src/pages/index.tsx
  src/styles/components/routine/RoutineLayout.module.scss
  src/types/routine.ts
  src/utils/getTimeLeftDisplay.ts
  src/utils/updateTaskStatusAndTimeLeft.ts
Labels: 기능구현

#52 design: 레이아웃 1차 개선 완료
  src/components/routine/NextRoutineLayout.tsx
  src/styles/components/routine/NextRoutineLayout.module.scss
Labels: 기능구현

#56 fix: build 오류 수정
  src/pages/banner/create/index.tsx
Labels: 오류수정

#53 Feat/14 배너 상세페이지 구현
  src/apis/getBannerItem.ts
  src/apis/postCalender.ts
  src/apis/postComment.ts
  src/apis/postDeleteComment.ts
  src/apis/postLike.ts
  src/components/banner/BannerItem.tsx
  src/components/banner/detail/CommentItem.tsx
  src/components/banner/detail/CommentList.tsx
  src/components/banner/detail/DetailButtons.tsx
  src/components/banner/detail/DetailTitle.tsx
  src/pages/api/v1/banners/custom/[id]/comments/index.ts
  src/pages/api/v1/banners/custom/[id]/index.ts
  src/pages/api/v1/banners/custom/[id]/tasks/index.ts
  src/pages/api/v1/banners/custom/comments/[id]/index.ts
  src/pages/api/v1/banners/custom/comments/[id]/likes/index.ts
  src/pages/banner/detail/[id].tsx
  src/types/banner.ts
Labels: 기능구현

#62 Feat/54 Routine api spec, type, mock data 생성
  src/apis/tasks/deleteMemberSharedRoutine.ts
  src/apis/tasks/deleteRoutine.ts
  src/apis/tasks/getMemberSharedRoutine.ts
  src/apis/tasks/getRoutineListMonthly.ts
  src/apis/tasks/getRoutineOne.ts
  src/apis/tasks/postMemberSharedRoutine.ts
  src/apis/tasks/postRoutine.ts
  src/apis/tasks/putRoutine.ts
  src/pages/api/v1/tasks/list.ts
  src/pages/api/v1/tasks/shared-member.ts
  src/types/routine.ts
Labels: 기능구현

#61 Refactor/60 헤더 컴포넌트 수정
  src/components/README.md
  src/components/common/Header.tsx
  src/pages/_app.tsx
  src/pages/banner/list/[page].tsx
  src/pages/index.tsx
  src/styles/components/common/Header.module.scss
  src/styles/globals.scss
Labels: 기능구현, 리펙토링

#65 Refactor/59 배너 리스트 페이지 ui 수정 및 기능 추가
  package.json
  src/components/banner/BannerFilter.tsx
  src/components/banner/BannerItem.tsx
  src/components/banner/BannerPaginate.tsx
  src/components/banner/BannerSlider.tsx
  src/components/common/Header.tsx
  src/pages/api/v1/banners/page/[page]/index.ts
  src/pages/banner/list/[page].tsx
  src/styles/components/banner/BannerFilter.module.scss
  src/styles/components/banner/BannerItem.module.scss
  src/styles/components/banner/BannerList.module.scss
  src/styles/components/banner/BannerPaginate.module.scss
  src/styles/components/banner/BannerSlider.module.scss
  src/styles/components/common/Header.module.scss
  src/styles/globals.scss
  src/styles/pages/BannerListPage.module.scss
  yarn.lock
Labels: 기능구현, 리펙토링

#66 Feat/63
  src/apis/member/deleteMemberSharedRoutine.ts
  src/apis/member/getMemberSharedRoutine.ts
  src/apis/member/postMemberSharedRoutine.ts
  src/apis/tasks/deleteRoutine.ts
  src/apis/tasks/getRoutineListMonthly.ts
  src/apis/tasks/getRoutineOne.ts
  src/apis/tasks/postRoutine.ts
  src/apis/tasks/putRoutine.ts
  src/components/calendar/Calendar.tsx
  src/components/routine/NextRoutineLayout.tsx
  src/pages/api/v1/tasks/[number].ts
  src/pages/api/v1/tasks/list.ts
  src/pages/api/v1/tasks/shared-member.ts
Labels: 기능구현

#70 Feat/67 Routine 관련 API 연결(postRoutine 연결)
  src/apis/tasks/postRoutine.ts
  src/components/routine/RoutineLayout.tsx
  src/pages/api/v1/tasks/index.ts
  src/types/routine.ts
Labels: 기능구현

#73 Feat/71 메인페이지 레이아웃 다듬기
  public/background.png
  src/styles/components/calendar/Calendar.module.scss
  src/styles/components/routine/NextRoutineLayout.module.scss
  src/styles/components/routine/RoutineLayout.module.scss
  src/styles/components/user/UserInfoMainLayout.module.scss
  src/styles/pages/MainPage.module.scss
Labels: 기능구현

#75 feat/72 Calendar Today 버튼 누를 시 오늘 날짜 누른 듯한 효과 넣기
  src/components/calendar/Calendar.tsx
Labels: 기능구현

#76 Feat/69 api putRoutine, deleteRoutine 연결
  src/components/routine/RoutineLayout.tsx
  src/pages/index.tsx
  src/types/routine.ts
Labels: 기능구현

#78 Feat/77 배너 일정 API 생성
  src/apis/tasks/deleteBannerRoutine.ts
  src/apis/tasks/getBannerRoutineListMonthly.ts
  src/apis/tasks/postBannerRoutine.ts
  src/pages/api/v1/banners/custom/mybanners/list.ts
  src/types/routine.ts
Labels: 기능구현

#80 Refactor/79 메인페이지 배너레이아웃 이미지 슬라이드 네비게이션 hooks 모듈화
  src/components/banner/BannerMainLayout.tsx
  src/hooks/README.md
  src/hooks/useSlideNavigation.ts
  src/utils/README.md
Labels: 리펙토링

#81 Feat/50 Calendar 기능수정/추가 + 메인 페이지 디자인 다듬기
  public/temp_images/BannerTempImage1.png
  public/temp_images/BannerTempImage2.png
  public/temp_images/BannerTempImage3.png
  public/temp_images/BannerTempImage4.png
  public/temp_images/BannerTempImage5.png
  src/components/calendar/Calendar.tsx
  src/components/calendar/CalendarTable.tsx
  src/components/calendar/MonthYearSelector.tsx
  src/pages/api/v1/mybanners/list.ts
  src/pages/api/v1/tasks/list.ts
  src/styles/components/calendar/Calendar.module.scss
  src/styles/components/calendar/MonthYearSelector.module.scss
  src/styles/components/routine/RoutineLayout.module.scss
  src/utils/calendarUtils.ts
Labels: 기능구현
