Repository Techeer-FM-Studio/frontend, pull requests merged in 2023-06, with the labels that each got.

#88 Design/86 폴더 구조 정리 / 코드 네이밍 컨벤션 - 배너 관련
  .gitignore
  .gitmessage.txt
  src/apis/banner.ts
  src/apis/comment.ts
  src/apis/customAxios.ts
  src/apis/deleteBannerInfo.ts
  src/apis/deleteMyBanners.ts
  src/apis/fetchTaskData.ts
  src/apis/getBannerItem.ts
  src/apis/getBannerList.ts
  src/apis/getComments.ts
  src/apis/getNextRoutine.ts
  src/apis/image.ts
  src/apis/like.ts
  src/apis/postBannerInfo.ts
  src/apis/postCalender.ts
  src/apis/postComment.ts
  src/apis/postDeleteComment.ts
  src/apis/postMyBanners.ts
  src/apis/tasks/deleteBannerRoutine.ts
  src/apis/tasks/deleteRoutine.ts
  src/apis/tasks/getBannerRoutineListMonthly.ts
  src/apis/tasks/getRoutineListMonthly.ts
  src/apis/tasks/getRoutineOne.ts
  src/apis/tasks/postBannerRoutine.ts
  src/apis/tasks/postRoutine.ts
  src/apis/tasks/putRoutine.ts
  src/assets/README.md
  src/components/banner/Comment/Item/index.tsx
  src/components/banner/Comment/Item/styles.module.scss
  src/components/banner/Comment/List/index.tsx
  src/components/banner/Comment/List/styles.module.scss
  src/components/banner/Detail/Button/index.tsx
  src/components/banner/Detail/Button/styles.module.scss
  src/components/banner/Detail/Title/index.tsx
  src/components/banner/Detail/Title/styles.module.scss
  src/components/banner/Filter/index.tsx
  src/components/banner/Filter/styles.module.scss
  src/components/banner/Info/index.tsx
  src/components/banner/Info/styles.module.scss
  src/components/banner/Item/index.tsx
  src/components/banner/Item/styles.module.scss
  src/components/banner/List/index.tsx
  src/components/banner/List/styles.module.scss
  src/components/banner/Paginate/index.tsx
  src/components/banner/Paginate/styles.module.scss
  src/components/banner/Slider/index.tsx
  src/components/banner/Slider/styles.module.scss
  src/components/common/Header/index.tsx
  src/components/common/Header/styles.module.scss
  src/constants/banner.ts
  src/pages/banner/detail/[id].tsx
  src/pages/banner/detail/styles.module.scss
  src/pages/banner/list/[page].tsx
  src/pages/banner/list/styles.module.scss
  src/pages/banner/write/index.tsx
  src/pages/banner/write/styles.module.scss
  src/pages/index.tsx
  src/types/banner.ts
Labels: FEAT, CHORE

#90 Chore/89 폴더구조 리팩토링 / 코드 네이밍 컨벤션 - 메인 관련
  .husky/pre-commit
  src/apis/routine.ts
  src/assets/Logo.png
  src/assets/background.png
  src/assets/temp_images/BannerTempImage1.png
  src/assets/temp_images/BannerTempImage2.png
  src/assets/temp_images/BannerTempImage3.png
  src/assets/temp_images/BannerTempImage4.png
  src/assets/temp_images/BannerTempImage5.png
  src/assets/temp_images/UserInfoTempImage.png
  src/components/banner/Item/index.tsx
  src/components/banner/MainSlider/index.tsx
  src/components/banner/MainSlider/styles.module.scss
  src/components/calendar/Calendar/index.tsx
  src/components/calendar/Calendar/styles.module.scss
  src/components/calendar/CalendarTable/index.tsx
  src/components/calendar/MonthYearSelector/index.tsx
  src/components/calendar/MonthYearSelector/styles.module.scss
  src/components/common/Header/index.tsx
  src/components/routine/Main/index.tsx
  src/components/routine/Main/styles.module.scss
  src/components/routine/Special/index.tsx
  src/components/routine/Special/styles.module.scss
  src/components/user/MainInfo/index.tsx
  src/components/user/MainInfo/styles.module.scss
  src/hooks/useSlideNavigation.ts
  src/pages/api/v1/banners/custom/mybanners/list.ts
  src/pages/api/v1/tasks/[number].ts
  src/pages/api/v1/tasks/index.ts
  src/pages/api/v1/tasks/list.ts
  src/pages/banner/detail/[id].tsx
  src/pages/banner/list/[page].tsx
  src/pages/index.tsx
  src/styles/pages/MainPage.module.scss
  src/types/routine.ts
  src/utils/calendarUtils.ts
Labels: REFACT

#96 Feat/93 로그인 UI 구현
  package.json
  src/apis/tasks/getBannerRoutineListMonthly.ts
  src/apis/tasks/getRoutineListMonthly.ts
  src/apis/tasks/getRoutineOne.ts
  src/apis/tasks/postBannerRoutine.ts
  src/apis/tasks/postRoutine.ts
  src/apis/tasks/putRoutine.ts
  src/components/Auth/index.tsx
  src/components/Sign/SignIn/index.tsx
  src/components/Sign/SignIn/styles.module.scss
  src/components/Sign/SignUp/index.tsx
  src/pages/_app.tsx
  src/pages/banner/detail/[id].tsx
  src/pages/banner/list/[page].tsx
  src/pages/index.tsx
  src/pages/sign/index.tsx
  src/pages/sign/styles.module.scss
  src/store/store.ts
  src/utils/updateTaskStatusAndTimeLeft.ts
  yarn.lock
Labels: FEAT, FIX
